### ISSUE TITLE
Forked version does not update within OBS

### ISSUE THREAD

**Issue by Plat-Chat** [RCVolus/obs-google-sheet-importer#12]
This application is awesome and works flawlessly with my google sheets.

However, I can't seem to get the sources to updated in the recommended forked version by DaBenjamins. Apologies if this report is in the wrong place, I'm not sure how to report this potential bug for a forked version.

Upon running the start.bat it indicates that everything is connected properly and being read from my sheet but OBS is not updating the sources. I've tried the formatting that was recommended in the readme and made sure that the cell I am trying to read from is within the rage in the config.json file. My sources are not in groups and I have yet to try anything other than text sources.

![cmd_8WFILrbgTD](https://github.com/RCVolus/obs-google-sheet-importer/assets/146778421/5fbd686e-b731-4dbf-9959-9a189cf82e0a)

Is there anything I'm doing wrong here?

**Comment by heinmastenbroek** [comment]
I'm seem to be having the same issue with OBS 29.1.3 on OSX. Sheet is being read OK, Data is being pulled in correct from API in the terminal index.js. Websocket is connected and messages in/out are updated but no luck when adding a text in sources with the format testtext |sheet B3. Any suggestions?

**Comment by heinmastenbroek** [comment]
Not in the forked version but master I may add.

**Comment by Unillu** [comment]
I'm having the same issue. Able to connect to google sheet, shows as connected in terminal and values are populating correctly. Not showing text from sheet, however.
MacBook Pro, Ventura 13.6.1
OBS 30.0.2

My sheet: https://docs.google.com/spreadsheets/d/1LtjHGiq0gWwNLRhhJgJzllySpkTAx7LJnwWG3BBm_js/edit?usp=sharing

My text layer calling cell F5: Player Name Left |sheet F5

**Comment by jarbochov** [comment]
I am also running into this issue on MacOS.

**Comment by jarbochov** [comment]
Okay, I know enough to be dangerous, but for Mac OS it still uses Freetype 2 and not GDI+. I am able to get the text to update if I replace:

`      if (source.sourceName.includes('|sheet') && source.inputKind.includes('gdiplus')) {`

with

`      if (source.sourceName.includes('|sheet') && source.inputKind.includes('ft2')) {`

but then it errors out with:

`TypeError: Cannot read properties of undefined (reading 'startsWith')
    at /Users/jarbochov/Library/CloudStorage/GoogleDrive-jared.cherup@gmail.com/My Drive/Projects/Twitch/OBS Scripts/obs-google-sheet-importer-master/index.js:47:29
    at Array.forEach (<anonymous>)
    at /Users/jarbochov/Library/CloudStorage/GoogleDrive-jared.cherup@gmail.com/My Drive/Projects/Twitch/OBS Scripts/obs-google-sheet-importer-master/index.js:32:33
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`
      
 I am not sure if that's helpful, but I'm closer.

**Comment by jarbochov** [comment]
Okay, I know enough to be dangerous, but for Mac OS it still uses Freetype 2 and not GDI+. I am able to get the text to update if I replace:

`      if (source.sourceName.includes('|sheet') && source.inputKind.includes('gdiplus')) {`

with

`      if (source.sourceName.includes('|sheet') && source.inputKind.includes('ft2')) {
`
but then it errors out with:

`TypeError: Cannot read properties of undefined (reading 'startsWith') at /Users/jarbochov/Library/CloudStorage/GoogleDrive/My Drive/Projects/Twitch/OBS Scripts/obs-google-sheet-importer-master/index.js:47:29 at Array.forEach (<anonymous>) at /Users/jarbochov/Library/CloudStorage/GoogleDrive/My Drive/Projects/Twitch/OBS Scripts/obs-google-sheet-importer-master/index.js:32:33 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

I am not sure if that's helpful, but I'm closer.

**Comment by jarbochov** [comment]
Okay, my bad. I had another scene referencing cells outside the scope. 

I can confirm on MacOS the change to `ft2` works.  Hopefully this is helpful.
